spring:
    datasource:
        password: ''
        url: jdbc:mysql://127.0.0.1:3306/user_project_db
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
            show-sql: true





